name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت پروژه
        uses: actions/checkout@v4

      - name: نصب Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: نصب Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: ساخت APK
        run: |
          buildozer android debug

      - name: دریافت APK
        uses: actions/upload-artifact@v4
        with:
          name: hossein-app
          path: bin/*.apk